import { uid } from './helpers';

const SAMPLE_INVOICES = [
  {
    id: 'RT3080',
    createdAt: '2021-08-18',
    paymentDue: '2021-09-19',
    description: 'Re-branding',
    paymentTerms: 1,
    clientName: 'Jensen Huang',
    clientEmail: 'jensenh@mail.com',
    status: 'paid',
    senderAddress: {
      street: '19 Union Terrace',
      city: 'London',
      postCode: 'E1 3EZ',
      country: 'United Kingdom',
    },
    clientAddress: {
      street: '106 Kendell Street',
      city: 'Sharrington',
      postCode: 'NR24 5WQ',
      country: 'United Kingdom',
    },
    items: [
      { id: uid(), name: 'Brand Guidelines', quantity: 1, price: 1800.90, total: 1800.90 },
    ],
    total: 1800.90,
  },
  {
    id: 'XM9141',
    createdAt: '2021-08-21',
    paymentDue: '2021-09-20',
    description: 'Graphic Design',
    paymentTerms: 30,
    clientName: 'Alex Grim',
    clientEmail: 'alexgrim@mail.com',
    status: 'pending',
    senderAddress: {
      street: '19 Union Terrace',
      city: 'London',
      postCode: 'E1 3EZ',
      country: 'United Kingdom',
    },
    clientAddress: {
      street: '84 Church Way',
      city: 'Bradford',
      postCode: 'BD1 9PB',
      country: 'United Kingdom',
    },
    items: [
      { id: uid(), name: 'Banner Design', quantity: 1, price: 156.00, total: 156.00 },
      { id: uid(), name: 'Email Design',  quantity: 2, price: 200.00, total: 400.00 },
    ],
    total: 556.00,
  },
  {
    id: 'RG0314',
    createdAt: '2021-09-01',
    paymentDue: '2021-09-01',
    description: 'Website Redesign',
    paymentTerms: 1,
    clientName: 'John Morrison',
    clientEmail: 'jm@myco.com',
    status: 'paid',
    senderAddress: {
      street: '19 Union Terrace',
      city: 'London',
      postCode: 'E1 3EZ',
      country: 'United Kingdom',
    },
    clientAddress: {
      street: '2 Stratford Court',
      city: 'Cowridge',
      postCode: 'MK9 3LT',
      country: 'United Kingdom',
    },
    items: [
      { id: uid(), name: 'Website Redesign', quantity: 1, price: 14002.33, total: 14002.33 },
    ],
    total: 14002.33,
  },
  {
    id: 'RT2080',
    createdAt: '2021-09-05',
    paymentDue: '2021-10-05',
    description: 'Logo Concept',
    paymentTerms: 30,
    clientName: 'Alysa Werner',
    clientEmail: 'alysa@email.co.uk',
    status: 'pending',
    senderAddress: {
      street: '19 Union Terrace',
      city: 'London',
      postCode: 'E1 3EZ',
      country: 'United Kingdom',
    },
    clientAddress: {
      street: '63 Warwick Road',
      city: 'Carlisle',
      postCode: 'CA20 2TF',
      country: 'United Kingdom',
    },
    items: [
      { id: uid(), name: 'Logo Sketches', quantity: 1, price: 102.04, total: 102.04 },
    ],
    total: 102.04,
  },
  {
    id: 'AA1449',
    createdAt: '2021-09-07',
    paymentDue: '2021-10-07',
    description: 'Re-branding',
    paymentTerms: 7,
    clientName: 'Mellisa Clarke',
    clientEmail: 'mellisa.clarke@example.com',
    status: 'pending',
    senderAddress: {
      street: '19 Union Terrace',
      city: 'London',
      postCode: 'E1 3EZ',
      country: 'United Kingdom',
    },
    clientAddress: {
      street: '46 Abbey Row',
      city: 'Cambridge',
      postCode: 'CB5 6EG',
      country: 'United Kingdom',
    },
    items: [
      { id: uid(), name: 'New Logo',        quantity: 1, price: 1532.33, total: 1532.33 },
      { id: uid(), name: 'Brand Guidelines',quantity: 1, price: 2500.00, total: 2500.00 },
    ],
    total: 4032.33,
  },
  {
    id: 'TY9141',
    createdAt: '2021-10-01',
    paymentDue: '2021-10-31',
    description: 'Monthly Retainer',
    paymentTerms: 30,
    clientName: 'Thomas Wayne',
    clientEmail: 'thomas@dc.com',
    status: 'draft',
    senderAddress: {
      street: '19 Union Terrace',
      city: 'London',
      postCode: 'E1 3EZ',
      country: 'United Kingdom',
    },
    clientAddress: {
      street: '3940 Prospect Road',
      city: 'Gotham',
      postCode: 'GC1 23A',
      country: 'United States',
    },
    items: [
      { id: uid(), name: 'Monthly Services', quantity: 1, price: 400.00, total: 400.00 },
    ],
    total: 400.00,
  },
];

export default SAMPLE_INVOICES;
